# Generated by Django 5.0.1 on 2024-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_postmodel_moderate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_moderate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
