# Generated by Django 5.0.1 on 2024-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_postmodel_date_moderate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='moderate',
            field=models.CharField(choices=[('M', 'Опубликовано'), ('W', 'На модерации'), ('U', 'Отклонено'), ('D', 'На удаление')], default='u', max_length=1, null=True, verbose_name='Модерация'),
        ),
    ]
