# Generated by Django 5.0.1 on 2024-02-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_postmodel_moderate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'permissions': (('moderate', 'Можем модерировать объявление'),)},
        ),
    ]
