# Generated by Django 5.0.1 on 2024-02-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_commentmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['date_add']},
        ),
    ]
